# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockerid', models.CharField(max_length=50)),
                ('port_total', models.IntegerField(default=12)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('actived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('USED', 'In using'), ('PENDING', 'Pending for confirm'), ('RESERVED', 'Reserved for tag')], default='PENDING', max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker_list', to='locker.Group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LockerPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portid', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('actived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('USED', 'In using'), ('PENDING', 'Pending for confirm'), ('RESERVED', 'Reserved for tag')], default='PENDING', max_length=50)),
                ('lockerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockerport_list', to='locker.Locker')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReserveLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('lockerport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_lockerport_list', to='locker.LockerPort')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(max_length=100)),
                ('tagtype', models.CharField(choices=[('USER', 'Normal user'), ('ADMIN', 'Administrator')], default='USER', max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('actived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('USED', 'In using'), ('PENDING', 'Pending for confirm'), ('RESERVED', 'Reserved for tag')], default='PENDING', max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservelocker',
            name='tagid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tag_list', to='locker.Tag'),
        ),
        migrations.AddField(
            model_name='reservelocker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
